"""
╔══════════════════════════════════════════════════════════════╗
║  Topic 15 — Agents                                           ║
║  File:   02_agent_patterns.py                                ║
║  Level:  Advanced                                            ║
║  Goal:   Multi-tool agents, agent with memory, stopping      ║
║          conditions, and production agent patterns           ║
╚══════════════════════════════════════════════════════════════╝
"""

from dotenv import load_dotenv
load_dotenv()

from langchain_openai import ChatOpenAI
from langchain_core.tools import tool
from langchain_core.messages import HumanMessage, SystemMessage
from langgraph.prebuilt import create_react_agent
from langgraph.checkpoint.memory import MemorySaver

llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)

print("=" * 60)
print("15 — Agent Patterns")
print("=" * 60)

# Define a richer toolset
@tool
def search_knowledge(query: str) -> str:
    """Search the internal knowledge base for information."""
    kb = {
        "langchain": "LangChain is a framework for LLM apps, created by Harrison Chase in 2022.",
        "langgraph": "LangGraph builds stateful multi-agent graphs on top of LangChain.",
        "rag":       "RAG retrieves relevant docs before LLM generation to reduce hallucination.",
        "lcel":      "LCEL uses the | pipe operator to compose chains elegantly.",
    }
    for key, value in kb.items():
        if key in query.lower():
            return value
    return "No relevant information found in knowledge base."

@tool
def calculate(expression: str) -> str:
    """Evaluate a mathematical expression safely."""
    try:
        allowed = set("0123456789+-*/()., ")
        if not all(c in allowed for c in expression):
            return "Error: Invalid characters in expression"
        result = eval(expression, {"__builtins__": {}}, {})
        return str(round(result, 4))
    except Exception as e:
        return f"Error: {e}"

@tool
def format_report(title: str, content: str) -> str:
    """Format content into a structured markdown report."""
    return f"# {title}\n\n{content}\n\n---\n*Generated by AI Agent*"

tools = [search_knowledge, calculate, format_report]

# ─────────────────────────────────────────────────────────────
# PATTERN 1: Agent with persistent memory (same user across turns)
# ─────────────────────────────────────────────────────────────
print("\n📌 1. Agent with Persistent Memory")
print("─" * 40)

memory  = MemorySaver()
agent   = create_react_agent(llm, tools, checkpointer=memory)
config  = {"configurable": {"thread_id": "user_session_42"}}

turns = [
    "My name is Rahul and I'm learning LangChain.",
    "What is LangChain? Also what is 100 * 7?",
    "What's my name? And summarize what we discussed.",
]

for turn in turns:
    result = agent.invoke({"messages": [HumanMessage(turn)]}, config=config)
    answer = result["messages"][-1].content
    print(f"\n  User  : {turn}")
    print(f"  Agent : {answer[:120]}")

# ─────────────────────────────────────────────────────────────
# PATTERN 2: System Prompt to control agent behaviour
# ─────────────────────────────────────────────────────────────
print("\n📌 2. Agent with Constrained System Prompt")
print("─" * 40)

STRICT_SYSTEM = """You are a research assistant with ONE rule:
- ALWAYS use search_knowledge before answering factual questions
- NEVER answer from memory alone — always verify with a tool
- Format final answers as bullet points"""

strict_agent = create_react_agent(llm, tools, state_modifier=STRICT_SYSTEM)

result = strict_agent.invoke({
    "messages": [HumanMessage("Tell me about LangGraph and LCEL")]
})
print(f"  {result['messages'][-1].content[:300]}")

# ─────────────────────────────────────────────────────────────
# PATTERN 3: Tracking agent steps
# ─────────────────────────────────────────────────────────────
print("\n📌 3. Counting Agent Steps")
print("─" * 40)

result = agent.invoke(
    {"messages": [HumanMessage("Search for RAG and LangChain, then calculate 15 * 23.")]},
    config={"configurable": {"thread_id": "step_counter"}}
)

msgs  = result["messages"]
tools_called = [m for m in msgs if hasattr(m, "name")]
ai_msgs      = [m for m in msgs if hasattr(m, "tool_calls")]

print(f"  Total messages  : {len(msgs)}")
print(f"  Tool calls made : {len(tools_called)}")
print(f"  Final answer    : {msgs[-1].content[:100]}")

print("\n⚠️  Agent pattern tips:")
print("   • Use thread_id for per-user memory isolation")
print("   • Use system prompts to enforce agent behaviour rules")
print("   • Count steps/tool calls to detect stuck agents")
print("   • For prod: set max_iterations to prevent infinite loops")
